name: Fetch Latest Blog Post

on:
  schedule:
    - cron: '0 0 1 1-12 *'
  workflow_dispatch:

jobs:
 FecthBlogPosts:
    name: Fetch Blog Posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://jarmos.netlify.app/index.xml"
